name: Go Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.15.7'

    - name: Publish Docker Image
#      env:
#         USERNAME: ${{ secrets.USERNAME }}
#         PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        go version
        go get -v -d ./...
        go build -o usePost05 usePost05.go
        docker images

