name: Go Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: System Info
#      env:
#         SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      run: |
        wget -c https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
        export PATH=/usr/local/go/bin:$PATH
        uname -a
        mkdir bin
        ls -l
        go version
        go run hw.go
